export const GET_EPISODE_LIST_PENDING = 'GET_EPISODE_LIST_PENDING';
export const GET_EPISODE_LIST_FULFILLED = 'GET_EPISODE_LIST_FULFILLED';
export const GET_EPISODE_LIST_REJECTED = 'GET_EPISODE_LIST_REJECTED';

